### ISSUE TITLE
Question: Is there any pattern or reccomended way to use docopt.sh as Git submodule?

### ISSUE THREAD

**Issue by gerardbosch** [andsens/docopt.sh#13]
I've just found DOCOPT and I love it!
This is just a question, maybe even a nonsense :)

I was wondering if is there any pattern to use docopt.sh as a project dependency or on contrary is this kind of use discouraged. I couldn't manage to make it work in this way.

I mean, include docopt.sh repository as a Git submodule into another project to allow regenerating the parser on-the-fly and reacting to changes on the `$DOC` without requiring neither to install docopt separately via `pip3`, nor run it explicitly from command-line (`$ docopt.sh SCRIPT`).

The aim would be to be able to use someting like: `eval "$(./relative/path/to/docopt.sh --parser "$0")"` in a script, as the docopt.sh would be present as Git submodule.

If I'm not wrong, this would keep the script clean from parser-generated code. Sure for this to work, the script should live in its Git repository to maintain access to the parser (so no portable script). The aim would only be to allow other developers to quick modify the DOC options & run transparently without extra steps, always shipping the script as a Git repository.

**Comment by andsens** [comment]
Great to hear! Your usecase is a little beyond `docopt.sh`s intended scope.  
By using the [library mode](https://github.com/andsens/docopt.sh/tree/b6344e8cddfe99135eae9acefc85ed664d865227#library-mode) you should already be down to very little code (10 lines for a no-op program). If that is still too much you can also create a `get_args()` function and move it to the bottom of the file, so as to reduce visual clutter.

Even though the on-the-fly eval is meant for development, there's of course no harm in using it if you are fully aware of how things fit together. The biggest caveat would be that any developer that want's to use your script must have python installed and also the `docopt` and `termcolor` dependencies.

An alternative: `docopt.sh` tells `eval` to exit with `$? = 70` when either the library version or the `$DOC` hash don't match. However, it not only tells `eval` to do so (`printf "exit %d\n" "$code"`) but also exits with that same code itself.  
So instead of running `eval "$(docopt "$@")"` do this instead:
```
local code
code=$(docopt "$@")
if [[ $? -eq 70 ]]; then
    exec bash -c "docopt.sh \"$0\" && exec \"$0\" \$@" -- "$@"
fi
eval "$code"
```

This way you run the program like normal, but when the `$DOC` or lib check failes, the program bails with `exec`, updates itself, and then re-runs with the same arguments.
