### ISSUE TITLE
Shellcheck errors

### ISSUE THREAD

**Issue by impguard** [andsens/docopt.sh#14]
Running docopt over this help string:

```
DOC="Upload Tool.

Usage:
  ./upload.sh [-h]

Options:
  -h  Print this help string
"
```

I'm getting a littany of shellcheck errors. SC1009 for a parse error on "parse_long".  SC1056 for a "expected }". An undefined error on failure to parse this line `left=("${left[@]:0:$i}" "${left[@]:((i+1))}")`.

Despite these errors, the script runs fine, so either the minification confuses shellcheck. Unsure how to resolve if this is a shellcheck problem unable to properly parse the minified parser.

**Comment by andsens** [comment]
shellcheck definitely doesn't like minified code, and @koalaman explained in-depth why this is a "wontfix" ([see here](https://github.com/koalaman/shellcheck/issues/1584#issuecomment-493793119)).

*However*: That's why there's this code: https://github.com/andsens/docopt.sh/blob/7a221d7a05bb76cf09b6f4f2b53370aa92241849/docopt_sh/parser.py#L20-L34

Which shellcheck version are you running? With 0.7.1 not getting any errors on that code.  
It could also be the line-length that is set differently, could you maybe attach the entire file when you have run `docopt.sh` on it?

Closing for now, but please reopen it if you can reproduce this with the newest `docopt.sh` and `shellcheck`.
